### ISSUE TITLE
No logs when HuggingFace API key is not provided

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-huggingface#8]
In the case of the `apiKey` is not correctly provided (in the example below my secret is empty) there is no indication or guidance for the user.

![image](https://github.com/user-attachments/assets/d0850bfd-3926-42f9-8ccb-bca16aefd488)

```yaml
id: ai_assistant
namespace: company.team
inputs:
  - id: user_context
    type: STRING
tasks:
  - id: test
    type: io.kestra.plugin.huggingface.Inference
    model: facebook/bart-large-mnli
    apiKey: "{{ secret('HF_API_TOKEN') }}"
    inputs: "{{ inputs.user_context }}"
    parameters:
      candidate_labels:
          - "new discussion"
          - "follow up"
          - "discovery"
    waitForModel: true
```

### Environment

- Kestra Version: develop
